# Generated by Django 4.2.3 on 2023-10-02 17:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_lesson', models.CharField(max_length=100)),
                ('video', models.URLField()),
                ('time_video', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owners', models.CharField(db_index=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100, verbose_name='Тема')),
                ('time_create', models.DateTimeField(auto_now=True, verbose_name='Дата создания')),
                ('is_published', models.BooleanField(default=True, verbose_name='Публикация')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='lessons.lesson', verbose_name='Урок')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='lessons.owner', verbose_name='Владелец')),
            ],
            options={
                'verbose_name': 'Курсы',
                'verbose_name_plural': 'Курсы',
                'ordering': ['time_create'],
            },
        ),
        migrations.CreateModel(
            name='AllUsers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, verbose_name='Полбзователь')),
                ('time_watch', models.DateTimeField(auto_now_add=True, verbose_name='время просмотра')),
                ('is_viewed', models.BooleanField(default=True, verbose_name='Просмотрено')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='lessons.lesson', verbose_name='видео урока')),
            ],
        ),
    ]
