# Generated by Django 4.2.3 on 2023-10-04 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0002_categori_product_cat_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
