# Generated by Django 4.2.3 on 2023-10-04 09:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0004_allusers_date_allusers_ip_port_allusers_time_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(db_index=True, max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='cat_id',
        ),
        migrations.DeleteModel(
            name='Categori',
        ),
        migrations.AddField(
            model_name='product',
            name='cat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='lessons.category', verbose_name='Категория'),
        ),
    ]
