# Generated by Django 4.2.3 on 2023-10-04 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0005_category_remove_product_cat_id_delete_categori_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='time_create',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
    ]
