# Generated by Django 4.2.3 on 2023-10-04 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0006_alter_product_time_create'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='time_update',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата обновления'),
        ),
    ]
