# Generated by Django 4.2.3 on 2023-10-04 16:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0008_alter_lesson_options_lesson_is_published'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='allusers',
            options={'verbose_name': 'Пользователи ресурса', 'verbose_name_plural': 'Пользователи ресурса'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Категория', 'verbose_name_plural': 'Категория'},
        ),
        migrations.AlterModelOptions(
            name='owner',
            options={'verbose_name': 'Автор', 'verbose_name_plural': 'Автор'},
        ),
        migrations.AddField(
            model_name='lesson',
            name='slug',
            field=models.SlugField(max_length=255, null=True, unique=True, verbose_name='URL'),
        ),
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(max_length=255, null=True, unique=True, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='allusers',
            name='is_viewed',
            field=models.BooleanField(default=True, null=True, verbose_name='Просмотрено'),
        ),
        migrations.AlterField(
            model_name='allusers',
            name='time_watch',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='время просмотра'),
        ),
        migrations.AlterField(
            model_name='allusers',
            name='video',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='lessons.lesson', verbose_name='видео урока'),
        ),
        migrations.AlterField(
            model_name='category',
            name='category',
            field=models.CharField(db_index=True, max_length=20, verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='title_lesson',
            field=models.CharField(max_length=100, verbose_name='Название урока'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='video',
            field=models.URLField(verbose_name='Ссылка на видео'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='views',
            field=models.IntegerField(default=0, verbose_name='количество просмотров'),
        ),
        migrations.AlterField(
            model_name='owner',
            name='owners',
            field=models.CharField(db_index=True, max_length=100, verbose_name='Автор'),
        ),
    ]
